BEGIN;

INSERT INTO config.spam_measurement (field, regular_expression, label) VALUES
    ('stgu.first_given_name', '[\$¢£ƒ֏؋¥৲৳৻૱௹฿៛\u20A0-\u20CF]', 'currency symbols in first name'),
    ('stgu.first_given_name', '[[:upper:]]', 'upper-case letters in first name'),
    ('stgu.first_given_name', '-', 'hyphen in first name'),
    ('stgu.first_given_name', '\s', 'spaces in first name'),
    ('stgu.first_given_name', '\byou\b', 'literal word you in first name'),
    ('stgu.first_given_name', '\bfor\b', 'literal word for in first name'),
    ('stgu.first_given_name', '\bthe\b', 'literal word for in first name'),
    ('stgu.second_given_name', '[\$¢£ƒ֏؋¥৲৳৻૱௹฿៛\u20A0-\u20CF]', 'currency symbols in second name'),
    ('stgu.second_given_name', '[[:upper:]]', 'upper-case letters in second name'),
    ('stgu.second_given_name', '!', 'exclamation mark in second name'),
    ('stgu.second_given_name', '\s', 'spaces in second name'),
    ('stgu.second_given_name', '\byou\b', 'literal word you in first name'),
    ('stgu.second_given_name', '\bfor\b', 'literal word for in first name'),
    ('stgu.second_given_name', '\bthe\b', 'literal word for in first name'),
    ('stgu.family_name', '[\$¢£ƒ֏؋¥৲৳৻૱௹฿៛\u20A0-\u20CF]', 'currency symbols in family name'),
    ('stgu.family_name', '[[:upper:]]', 'upper-case letters in family name'),
    ('stgu.family_name', '\s', 'spaces in the family name'),
    ('stgu.family_name', '\byou\b', 'literal word you in first name'),
    ('stgu.family_name', '\bfor\b', 'literal word for in first name'),
    ('stgu.family_name', '\bthe\b', 'literal word for in first name'),
    ('stgma.street1', '[[:digit:]]', 'digits in the street 1'),
    ('stgma.street1', '!', 'exclamation marks in the street 1'),
    ('stgma.street1', '\s', 'spaces in the street 1'),
    ('stgma.city', '\byou\b', 'literal word you in the street 1'),
    ('stgma.city', '\bfor\b', 'literal word for in the street 1'),
    ('stgma.street1', '[\$¢£ƒ֏؋¥৲৳৻૱௹฿៛\u20A0-\u20CF]', 'currency symbols in the street 1'),
    ('stgma.city', '[[:alpha:]]$', 'city ends with letter'),
    ('stgma.city', '\byou\b', 'literal word you in city'),
    ('stgma.city', '\bfor\b', 'literal word for in city'),
    ('stgma.post_code', '[[:digit:]]', 'digits in post code'),
    ('stgma.post_code', '[[:alpha:]]', 'letters in post code'),
    ('stgma.post_code', '[[:punct:]]', 'punctuation in post code'),
    ('stgma.post_code', '\byou\b', 'literal word you in post code'),
    ('stgma.post_code', '\bfor\b', 'literal word for in post code'),
    ('stgma.post_code', '\bthe\b', 'literal word for in post code');

COMMIT;
