name: Run ng lint
on: [push, pull_request]
jobs:
  lint:
    name: Run Angular linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: Open-ILS/src/eg2/package-lock.json
      - name: lint
        run: cd Open-ILS/src/eg2 && npx ng lint
