name: Run ng lint
on: [push, pull_request]
defaults:
  run:
    working-directory: Open-ILS/src/eg2
jobs:
  lint:
    name: Run Angular linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: lint
        run: npx ng lint
