name: Run ng lint
on:
  push:
    paths:
      - 'Open-ILS/src/eg2/**'
  pull_request:
    paths:
      - 'Open-ILS/src/eg2/**'
jobs:
  lint:
    name: Run Angular linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
          cache: 'npm'
          cache-dependency-path: Open-ILS/src/eg2/package-lock.json
      - name: 
        run: cd Open-ILS/src/eg2 && npx ng lint
