name: Build evergreen and run tests
on: [push, pull_request]
jobs:
  install-opensrf:
    name: Install Opensrf
    runs-on: ubuntu-24.04
    steps:
      - name: Clone OpenSRF repository
        run: git clone --branch main git://git.evergreen-ils.org/OpenSRF.git
      - name: Install prereqs
        run: sudo make -f src/extras/Makefile.install ubuntu-jammy
        working-directory: ./opensrf
