name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'
jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-latest
    container:  node:latest
    strategy:
      matrix:
        pg-version: [13, 14, 15]
    services:
      postgres:
        image: postgres:${{ matrix.pg-version }}
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Setup pgTAP
        run: sudo cpan TAP::Parser::SourceHandler::pgTAP
      - name: Setup pgtap on database
        uses: actions/checkout@v2
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.1.0
      - name: Install pgtap on target
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres -c "CREATE EXTENSION pgtap;"
        env:
          PGPASSWORD: postgres
      - name: Build the database schema
        run: "Open-ILS/src/sql/Pg/build-db.sh localhost 5432 postgres postgres postgres 1"


# TODO:
# run that script
# run the sample data loader
# run pgtap
# run pgtap regress
# run pgtap live
# matrix of postgres versions
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?)
