name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'
jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pg-version: [13, 14, 15]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: install pg_prove
        run: sudo cpan -T TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: install postgres extensions and dependencies
        run: sudo apt update && sudo make -f Open-ILS/src/extras/Makefile.install postgres-server-ubuntu-jammy-14
      - name: Checkout pgtap
        uses: actions/checkout@v3
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0

      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: apt get lib dbi
        run: sudo apt update && sudo apt install -y libdbi-perl
      - name: prepare the eg_db_config script
        run: sed -e 's,[@]sysconfdir@,~,g'
      - name: install database
        run: perl Open-ILS/src/support-scripts/eg_db_config.in --update-config --service all --create-database --create-schema --create-offline --user postgres --password postgres --hostname localhost --database evergreen --admin-user admin --admin-pass demo123 --config_file Open-ILS/examples/opensrf.xml.example
      - name: install pgtap extension
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname evergreen --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: Build the database schema
        run: "./build-db.sh localhost 5432 evergreen postgres postgres 1"
        working-directory: ./Open-ILS/src/sql/Pg


# TODO:
# run that script successfully
# run the sample data loader
# run pgtap
# run pgtap regress
# run pgtap live
# refactor to use some kind of variable for db connection info, dirs
# matrix of postgres versions
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?)
