name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'

env:
  PGPASSWORD: postgres

jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pg-version: [13, 14, 15]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      # The Github actions jammy image comes with postgres 14 installed.  To test other postgres
      # versions, we need to remove 14 first
      - name: Delete the postgres 14 cluster that comes with the github actions ubuntu image
        run: sudo pg_dropcluster --stop 14 main
        if: matrix.pg-version != 14
      - name: Remove any postgres that is already installed in the github actions ubuntu image
        run: sudo apt remove -y postgres*
        if: matrix.pg-version != 14

      # Next, let's install dependencies
      - name: install postgres extensions and dependencies
        run: sudo make -f Open-ILS/src/extras/Makefile.install postgres-server-ubuntu-jammy-${{ matrix.pg-version }}
      - name: apt get lib dbi
        run: sudo apt update && sudo apt install -y libdbi-perl
      - name: install pg_prove
        run: sudo cpan -T TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: Checkout pgtap
        uses: actions/checkout@v4
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0

      # Start up postgres      
      - name: start postgres cluster
        run: sudo pg_ctlcluster ${{ matrix.pg-version }} main start
      - name: change postgres to a known password
        run: sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres'"

      # Create the needed database, extensions, schema, and data
      - name: install database extensions
        run: psql --host localhost --username postgres --file create_database_extensions.sql -v db_name=evergreen
        working-directory: Open-ILS/src/sql/Pg
      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
      - name: build database
        run: "./build-db.sh localhost 5432 evergreen postgres $PGPASSWORD 1"
        working-directory: Open-ILS/src/sql/Pg
      - name: load sample data
        run: psql --host localhost --username postgres --dbname evergreen --file load_all.sql
        working-directory: Open-ILS/tests/datasets/sql/concerto
      - name: install pgtap extension
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname evergreen --file sql/pgtap.sql

      # Now, let's run the tests!
      - name: run pgtap tests
        run: pg_prove --host localhost --username postgres --dbname evergreen t
        working-directory: Open-ILS/src/sql/Pg
      - name: run pgtap regression tests
        run: pg_prove --host localhost --username postgres --dbname evergreen t/regress
        working-directory: Open-ILS/src/sql/Pg
      - name: run pgtap live tests
        run: pg_prove --host localhost --username postgres --dbname evergreen live_t
        working-directory: Open-ILS/src/sql/Pg


# TODO:
# one way to simplify: create a script to setup and run pgtap tests, and call that
# another way to simplify: allow eg_db_config to be called without running opensrf
# refactor to use some kind of variable for db connection info, dirs
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?), or github actions dir
