name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'
jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pg-version: [13, 14, 15]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: install pg_prove
        run: sudo cpan -T TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: install postgres extensions and dependencies
        run: sudo make -f Open-ILS/src/extras/Makefile.install postgres-server-ubuntu-jammy-${{ matrix.pg-version }}
      - name: Checkout pgtap
        uses: actions/checkout@v3
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0
      - name: apt get lib dbi
        run: sudo apt update && sudo apt install -y libdbi-perl
      - name: change postgres to a known password
        run: sudo /etc/init.d/postgresql restart && psql --host localhost --username postgres -c "ALTER USER postgres WITH PASSWORD 'postgres'"
        env:
          PGPASSWORD: postgres
      - name: Which postgres version is there?
        run: psql --host localhost --username postgres -c 'SELECT version();'
        env:
          PGPASSWORD: postgres
      - name: install database extensions
        run: psql --host localhost --username postgres --file create_database_extensions.sql -v db_name=evergreen
        env:
          PGPASSWORD: postgres
        working-directory: Open-ILS/src/sql/Pg
      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: build database
        run: "./build-db.sh localhost 5432 evergreen postgres postgres 1"
        working-directory: Open-ILS/src/sql/Pg
      - name: load sample data
        run: psql --host localhost --username postgres --dbname evergreen --file load_all.sql
        working-directory: Open-ILS/tests/datasets/sql/concerto
        env:
          PGPASSWORD: postgres
      - name: install pgtap extension
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname evergreen --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: run pgtap tests
        run: pg_prove --host localhost --username postgres --dbname evergreen t
        working-directory: Open-ILS/src/sql/Pg
        env:
          PGPASSWORD: postgres
      - name: run pgtap regression tests
        run: pg_prove --host localhost --username postgres --dbname evergreen t/regress
        working-directory: Open-ILS/src/sql/Pg
        env:
          PGPASSWORD: postgres
      - name: run pgtap live tests
        run: pg_prove --host localhost --username postgres --dbname evergreen live_t
        working-directory: Open-ILS/src/sql/Pg
        env:
          PGPASSWORD: postgres


# TODO:
# refactor to use some kind of variable for db connection info, dirs
# matrix of postgres versions
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?)
