name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'
jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Build the database schema
        run: "Open-ILS/src/sql/Pg/build-db.sh postgres 5432 postgres postgres postgres 1"
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGDATABASE: postgres
          PGUSER: postgres
          PGPASSWORD: postgres

# TODO:
# run that script
# run the sample data loader
# run pgtap
# run pgtap regress
# run pgtap live
# matrix of postgres versions
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?)
