name: Run pgtap tests
on: push
# on:
#   push:
#     paths:
#       - 'Open-ILS/src/sql/**'
#   pull_request:
#     paths:
#       - 'Open-ILS/src/sql/**'
jobs:
  pgtap:
    name: Run PgTap tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        pg-version: [13, 14, 15]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: install pg_prove
        run: sudo cpan -T TAP::Parser::SourceHandler::pgTAP
        env:
          SHELL: /bin/bash
      - name: install postgres dev
        run: sudo apt update && sudo apt install -y --no-install-recommends postgresql-server-dev-14

      - name: Checkout pgtap
        uses: actions/checkout@v3
        with:
          repository: theory/pgtap
          path: pgtap
          ref: v1.2.0

      - name: install pgtap
        working-directory: pgtap
        run: make && psql --host localhost --username postgres --dbname postgres --file sql/pgtap.sql
        env:
          PGPASSWORD: postgres
      - name: install database extensions
        run: psql --host localhost --username postgres --dbname postgres --file create_database_extensions.sql 
        working-directory: ./Open-ILS/src/sql/Pg
        env:
          PGPASSWORD: postgres
      - name: Build the database schema
        run: "./build-db.sh localhost 5432 postgres postgres postgres 1"
        working-directory: ./Open-ILS/src/sql/Pg


# TODO:
# run that script
# run the sample data loader
# run pgtap
# run pgtap regress
# run pgtap live
# matrix of postgres versions
# setup to run only on changes to the db directory, sample data, or db script (or its dependencies, if it has some?)
