name: Release a new version of Evergreen
on:
  push:
  workflow_dispatch:

jobs:
  build_tarball:
    name: Build release tarball
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: sudo make -f Open-ILS/src/extras/Makefile.install ubuntu-noble-packager
      - name: Download OpenSRF javascript
        uses: actions/checkout@v4
        with:
          repository: evergreen-library-system/OpenSRF
          path: opensrf
      - name: Build tarball
        run: build/tools/make_release -b -j $(pwd)/../opensrf/src/javascript/
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ../release
