name: Release a new version of Evergreen
on:
  push:
    tags:        
      - '**'
  workflow_dispatch:

jobs:
  build_tarball:
    name: Build release tarball
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          path: build/Evergreen
      - name: Install prerequisites
        run: sudo make -f Open-ILS/src/extras/Makefile.install ubuntu-noble-packager
        working-directory: ./build/Evergreen
      - name: Build tarball
        run: build/tools/make_release -b
        working-directory: ./build/Evergreen
      - name: Store build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/release
          if-no-files-found: error
