name: Run tests
on: push
jobs:
  ng_lint:
    name: Lint the angular app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
      - run: cd Open-ILS/src/eg2 && npm i && ng lint
